//convert texture to GEO sequence

//inputs
string $filepath = "Z:/Job_2/Kinh Do/Maya/sourceimages/Silhouettes_HD/EiffleTower/eiffleTower_A003_C007_1029HB_001a_HD";
string $filename = "eiffleTower_A003_C007_1029HB_001a_HD";
string $fileExtension = "png";
int $framePadding = 3;

string $fullPath = ($filepath +"/"+ $filename +"."+ "005" + "." + $fileExtension);


//conversion
createTextureToGeom( $fullPath , "", "setTextureToGeomValues", 0 );
